// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg-viPVzNzfyJ5akzzHe2vtTWzeraUBOk',
    appId: '1:267269945666:web:af79a02013eb018d05f0db',
    messagingSenderId: '267269945666',
    projectId: 'fir-practice-7c20a',
    authDomain: 'fir-practice-7c20a.firebaseapp.com',
    storageBucket: 'fir-practice-7c20a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbr-R_O44a3Vtl1Rl-pMqenxDK5I79lQ',
    appId: '1:267269945666:android:52bbf3305fbb449c05f0db',
    messagingSenderId: '267269945666',
    projectId: 'fir-practice-7c20a',
    storageBucket: 'fir-practice-7c20a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXYdFd6rchGSw_6UJL6CY7eUQJrQUfyBY',
    appId: '1:267269945666:ios:c40453a85cc9c11f05f0db',
    messagingSenderId: '267269945666',
    projectId: 'fir-practice-7c20a',
    storageBucket: 'fir-practice-7c20a.appspot.com',
    iosClientId: '267269945666-m7nrfkj0pcocglmpgild4an2bsn1v1rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXYdFd6rchGSw_6UJL6CY7eUQJrQUfyBY',
    appId: '1:267269945666:ios:4dd9b797f5d196ef05f0db',
    messagingSenderId: '267269945666',
    projectId: 'fir-practice-7c20a',
    storageBucket: 'fir-practice-7c20a.appspot.com',
    iosClientId: '267269945666-7gb8vjthgdrq79pm65shs39vcamv34ie.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice.RunnerTests',
  );
}
